appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: O+hzDjOrNtB2091JJDPTD+SfQwAhGW8CUewRyvwgw3XPm4Z4Sx+qjF8nvqpK3d45FG25TgUtmWJthnOaTnSQWbvhzfqStGVKznluuOuSB70j3CegyR6a7M4JaY2agnrMQnDZeCxUxkF040VRcsRuevWu/TXId7tHUdurKHD8XJGlyazZ9qX8OTdAgSbmHxzk1c5CORD4Ra6L5JI13WU+6yZZfenGTTvXk5XtM/8lJYcUTwi+7rpQ97pR1wAK4AXVXggkLSDVGhLdWfnhe4ICwPghn4LMLDnHkrpJc4wmkgqBubQGC8COkGjoRxzpnKPsD+e2AWe5gfkCxdh12EqZREWuEs8vz6Fmv8LaxQnHU+FsIIHJHix72nYxEhrNwgONB3ugSwZLwSH3cIqD+J30/3X1TYOxvwA3Ss6qqK5alSz/S7sinn3mFBaDgG076KK+b5rQJ32oadgVfmHZ2XGJjg6s0hzRf+XZLxmA88ImcW0q7X0+OcyVTcpRqqpTn26orf8iH/I+c32OZM7a1RiB18/EtIjgiIOO5s5a0IdepupAHT67Mizpnj5sjJ8jNLGXO/wqzNEuQtp1inRnS8gxiMw+xYVvJv/EWRFsYLHnj5VndKsH0v1QEglt/qkTJ6/sGL5wibboT4xI35d9t/PktATehZWglS7dGaZn7uYekUE=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
