travis:
  secure:
    BINSTAR_TOKEN: OVdfZd1DHzJ2rtNMQ4vvGj0T8ECF8Ts6z2pm0755P3iire37+9nCw4lW4xBoD1WJFxpQvEry0lXLar31K5m80eP/n8JryM5UmgUYVwj4QJ/smykakP3mrDN2Pdw8HaQSA/ag3wOmCQpsCHGewjzExBG5cUzGiM8+vt7XTJYv+ufTjh+U8Q5dGAh7C+n7sueznpmaAqmrc5FOgjxpMZk8E920zJ77XU0Cs4WLLB+jPi5PPCk2PiYXETV+DBiWiV7MB4IwDp4/ToI1L+TA/AvZVmptd8nBrGd+2LeIF3BmodiSZ2E6ULD4j6TBu5AQ2ec2l1dckRn2zhhRaDZapzk0JXNXPZYS04sLoamhV2XUq6mjUwD5VxX6pDThJ3zoqnWbUk1TiJegQaR/3RSs4EtNUePDp5frMg30aUTxeRNApSTlLHbz4QnGjxUtQpAh3Kq6bJdFsRUbDD8JVPDY5zlPeonBFWl+oNMGvdeVp2l7bfTMLE9hrjb3qIPtLOIMx3WwYgRAKeWYeYhhY4BMlcUpVOC6YPsUOcEkyiV3m2hp7RQXwaIV36DF0B4G/pu6eXxmnNATzimjDiAwgV7m62N7D8pvFoxXKOCt8rFXUIZmkunWoNrVBXf0p4klDo92d+fSMtdmRWTaxK2DhtwygI4yHBU1qvS907E+ZRD6QgzDBsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
